[package]
name = "tuisky"
version = "0.1.0"
edition = "2021"

[dependencies]
atrium-api = "0.22.3"
bsky-sdk = "0.1.2"
chrono = { version = "0.4.38", default-features = false }
color-eyre = "0.6.3"
crossterm = { version = "0.27.0", features = ["event-stream"] }
futures-util = "0.3.30"
log = "0.4.21"
ratatui = "0.26.3"
tokio = { version = "1.38.0", features = [
    "macros",
    "rt-multi-thread",
    "sync",
    "time",
] }
tui-logger = "0.11.1"
tui-prompts = "0.3.12"
